#api end point

@baseurlproduct = http://localhost:8000/api/v1/products
#category url
@baseurlcategory = http://localhost:8000/api/v1/categories


###post product
POST {{baseurlproduct}}
Content-Type: application/json

{"name":"shekhar",
"price":200,
"category_id":"bread"
}

### get product
GET {{baseurlproduct}}
Content-Type: application/json




#categories 
### post category
POST {{baseurlcategory}}
Content-Type: application/json

{
  "name":"bread"
}
